apiVersion: v1
kind: Service
metadata:
  name: object-storage
  namespace: monsun
spec:
  ports:
    - port: 443
      targetPort: 9000
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio-tenant