apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: minio
    spec:
      hostname: minio
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: V42FCGRVMK24JJ8DHUYG
        - name: MINIO_SECRET_KEY
          value: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
        image: minio/minio
        # volumeMounts:
        # - mountPath: "/data"
        #   name: volume  
        name: minio
        ports:
        - containerPort: 9000
        resources: {}
      hostname: minio
      restartPolicy: Always
      serviceAccountName: ""
      # volumes:
      # - name: volume
      #   persistentVolumeClaim:
      #     claimName: azure-managed-disk
status: {}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: minio
  name: minio-service
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minio